name: Reusable CI Build

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        type: string
        default: '8.0.x'
      release-path:
        required: false
        type: string
        default: 'net8.0'
      build-configuration:
        required: false
        type: string
        default: 'Release'
      artifact-name:
        required: false
        type: string
        default: 'build-output'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration ${{ inputs.build-configuration }} --no-restore

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: '**/bin/${{ inputs.build-configuration }}/${{ inputs.release-path }}'
          if-no-files-found: error

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}

      - name: Display structure of downloaded files
        run: ls -R

      - name: Test
        run: dotnet test --no-restore --verbosity normal
